CREATE TABLE user(
    userId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(50) DEFAULT NULL,
    lastName VARCHAR(50) DEFAULT NULL,
    emailAddress VARCHAR(255) DEFAULT NULL,
    emailAddressLowerCase VARCHAR(255) DEFAULT NULL UNIQUE,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE userPasswordHash(
    userPasswordHashId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    userId INT UNSIGNED NOT NULL,
    passwordHash VARCHAR(255) NOT NULL,
    isDisabled INT(1) UNSIGNED NOT NULL DEFAULT 0,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE error(
    errorId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    type SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    message TEXT,
    file VARCHAR(255) DEFAULT NULL,
    line SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    uri VARCHAR(255) DEFAULT NULL,
    post INT(1) UNSIGNED NOT NULL DEFAULT 0,
    userId INT UNSIGNED NOT NULL DEFAULT 0,
    ipAddress VARCHAR(50) DEFAULT NULL,
    userAgent VARCHAR(255) DEFAULT NULL,
    referer VARCHAR(255) DEFAULT NULL,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE request(
    requestId INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    uri TINYTEXT,
    post INT(1) UNSIGNED NOT NULL DEFAULT 0,
    userId INT UNSIGNED NOT NULL DEFAULT 0,
    ipAddress VARCHAR(50) DEFAULT NULL,
    userAgent VARCHAR(255) DEFAULT NULL,
    referer VARCHAR(255) DEFAULT NULL,
    responseTime FLOAT(8, 4) UNSIGNED NOT NULL DEFAULT 0,
    numQueries INT UNSIGNED NOT NULL DEFAULT 0,
    created DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

